"""empty message

Revision ID: 3f056421d49b
Revises: cbe02cf3ee53
Create Date: 2021-02-11 19:59:04.554433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f056421d49b'
down_revision = 'cbe02cf3ee53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sa.String(length=100), nullable=True))
    op.drop_column('product', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('title', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('product', 'name')
    # ### end Alembic commands ###
