"""empty message

Revision ID: 48392099ce4e
Revises: 24d6759f3348
Create Date: 2021-02-18 20:11:31.982347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48392099ce4e'
down_revision = '24d6759f3348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_user')
    # ### end Alembic commands ###
