"""empty message

Revision ID: 945c8fb811d6
Revises: 414bedf5f008
Create Date: 2021-03-10 16:22:05.139868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945c8fb811d6'
down_revision = '414bedf5f008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'phone')
    # ### end Alembic commands ###
